### ISSUE TITLE
The solution of the regular-3

### ISSUE THREAD

**Issue by Domceng** [TensorBFS/TropicalTensors.jl#15]
When I reproduce your experiment on regular-3 graph using Gurobi, I obtain the energy less than that of tropical tensor network.

For example, I got the energy of 170 in ising.hdf5 (140 node and 1st seed ), but the energy computed by tropical tensor network is 174.

Could you provide the code of sampling (optimal spin configuration) for regular3 using tropical tensor network, just like spinglass, chimera, etc, so that I can verify your solution?

**Comment by GiggleLiu** [comment]
Thanks for the issue. Have you checked convensions of signs of coupling strengh and taking minimum/maximum. These are common reasons of inconsistency.

**Comment by Domceng** [comment]
请问耦合系数矩阵全是正的吗, 如果有正负之分的话, 这个信息存在ising.hdf5文件的什么位置?

**Comment by GiggleLiu** [comment]
If you check the loaded data, you will see
```julia
julia> loadeddata["n140"]["seed1"]
📂 HDF5.Group: /n140/seed1 (file: TropicalTensors/data/ising.hdf5)
├─ 🔢 complexity
├─ 🔢 edges
├─ 🔢 entros
├─ 🔢 interactions
├─ 🔢 labels
├─ 🔢 order
└─ 🔢 tensors
```

The edges and interactions are defined in "edges" and "interactions", they have one to one correspondence.

If you check the interaction matrix, and find it having the form
```julia
[:, :, 3] =
 -1   1
  1  -1
```
The coupling is FM. The program always finds the **highest** energy.

Otherwise if in the form
```julia
[:, :, 209] =
  1  -1
 -1   1
```
The coupling is AFM.

**Comment by Domceng** [comment]
Thanks, I have reproduced your results using Gurobi.
